# Generated by Django 4.2.16 on 2024-11-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_commitment_job_contact_job_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='seasons',
        ),
        migrations.AddField(
            model_name='job',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_season', to='api.season'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
