# Generated by Django 4.2.16 on 2024-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_job_seasons_job_season_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='during',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Year-round', 'Year-round'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('Director', 'Director'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='mode',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Application', 'Application'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Pending', 'Pending'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Opening soon', 'Opening soon'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Fellowship', 'Fellowship'), ('Other', 'Other'), ('', 'None')], max_length=100, null=True),
        ),
    ]
