# Generated by Django 4.2.16 on 2024-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_job_during_alter_job_level_alter_job_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Upcoming', 'Upcoming')], max_length=100, null=True),
        ),
    ]
