# Generated by Django 4.2.16 on 2024-12-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_job_commitment_remove_job_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Withdrawn', 'Withdrawn'), ('Other', 'Other'), ('', 'None')], max_length=200, null=True),
        ),
    ]
