# Generated by Django 4.2.16 on 2024-12-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
