# Generated by Django 4.2.16 on 2024-12-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
