# Generated by Django 4.2.16 on 2024-12-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='season',
            name='number_jobs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
