# Generated by Django 4.2.16 on 2024-12-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_season_start_date_alter_season_number_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education',
        ),
    ]
