# Generated by Django 4.2.16 on 2024-12-30 18:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_job_contact_remove_job_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='number',
        ),
        migrations.RemoveField(
            model_name='season',
            name='number_jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='during',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Year-round', 'Year-round'), ('Other', 'Other'), ('', 'None')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager'), ('Director', 'Director'), ('Other', 'Other'), ('', 'None')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='mode',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Other', 'Other'), ('', 'None')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Withdrawn', 'Withdrawn'), ('Other', 'Other'), ('', 'None')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Other', 'Other'), ('', 'None')], max_length=500, null=True),
        ),
    ]
